### ISSUE TITLE
[BUG MAJOR] Level 3 Desks Missing

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#137]
**Describe the bug**
The desks on level 3 are missing

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 3
2. go into the office
3. See desks are gone

**Expected behaviour**
The desks should be present in their respective place

**Screenshots**
![Level3DesksMissing](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/515a0496-74dd-4a94-9cc0-b20aaaf27b31)

**Game build numb**
0.0.10

**Comment by Soph65536** [comment]
added desks
