### ISSUE TITLE
Missing furniture

### ISSUE THREAD

**Issue by AshExistsSometimes** [Smash-Keyboard-Studios/Meltdown#147]
All Tables and Filing cabinets are missing

![NoTablesorCabinets](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156530724/9ba79760-6ee7-4005-a425-8e65b8a84494)

**Game build num**
0.0.11

**Additional context**
This makes the ice tutorial level impossible to complete

**Comment by domibron** [comment]
check this

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.17
