### ISSUE TITLE
Old Industrial Level

### ISSUE THREAD

**Issue by AshExistsSometimes** [Smash-Keyboard-Studios/Meltdown#148]
Current build uses an incomplete version of the Industrial level somehow, even though this level was entirely build between 0.0.10 and 0.0.11, there is a crouch cave missing behind the staircase, drill and minecart fbx's are missing from the cave portion, bed and curtain fbx's missing from infirmary, props in design office missing and all markers placed for puzzles and narrative locations, as well as the room names, are missing

**Game build num**
0.0.11

**Comment by domibron** [comment]
Check this still exsists

**Comment by domibron** [comment]
Not sure, dismissing issue
