### ISSUE TITLE
[Issue] Level 1 + 2 Wall textures

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#149]
**Describe the bug**
Many of the wall textures for level 1 and 2 are squashed and stretched

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 1 or 2
2. go to effected walls
3. See Issue

**Expected behavior**
The textures for the walls should be fitted perfectly

**Screenshots**
![Level 1 Textures](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/8854ed73-841e-4e7e-bcbf-7dab544ab546)

**Game build num**
0.0.11

**Comment by domibron** [comment]
Those walls need to be replaced all together now. is it design or art holding it back?

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.17
