### ISSUE TITLE
[BUG] Z fighting

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#150]
**Describe the bug**
There are instances of Z fighting in level 2, 4, 5, 6, 8 and 9.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into stated levels
2. Find walls or floors that intersect
3. See error

**Expected behaviour**
There shouldn't be any Z fighting

**Screenshots**
![Level 2 Z fighting 2](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/f82aee8c-a10d-4772-8275-af919de0b618)
![Level 2 Z fighting](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/465212ed-d429-4ee2-946e-3d45ca2a1957)

![Z Fighting L4](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/bbde4e3b-28e9-4d7f-a4ff-3474ccf8236b)

![Z Fight 5](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/6419611d-bd98-4d16-9d62-115905184a43)
![Z Fight And Door](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/625b6043-8c45-48d6-b712-42e497a23710)

![L9 Z fighting](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/871c53fa-549b-4e9b-b7d2-5b42bca74b86)

![L8 Z fighting](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/4b30e6ba-ec48-4497-9750-0cb92ca8f792)

![L6 Z fighting](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/c90d8b74-d5e6-4cda-906e-2e7637a09e63)

**Game build num**
0.0.17

**Comment by MathewHakwkins** [comment]
Still present as of 0.0.14

**Comment by MathewHakwkins** [comment]
Still Z Fighting as of 0.0.15

**Comment by MathewHakwkins** [comment]
Still Z fighting as of 0.0.16

**Comment by domibron** [comment]
dought this will ever go away

**Comment by RevisedDA** [comment]
This Z fighting issue is caused by the lacking environment art assets.

Office environment pack is completed and should resolve the office walls

In progress:
Warehouse Environment pack
Cave Environment pack

Fixing:
Lab Environment Pack
