### ISSUE TITLE
[BUG] Lift doors don't open

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#151]
**Describe the bug**
On level 5, the lift doors do not open meaning the player will need to use the debug menu to leave.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter level 5
2. See lift doors don't open

**Expected behavior**
The lift doors should open automatically when the player loads in 

**Screenshots**
![Level 3 Lift Doors dont open](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/1415aa46-3fb5-4f9c-b5ef-8695220a47bb)

**Game build num**
0.0.11

**Comment by MathewHakwkins** [comment]
Issue is still present in version 0.0.12

**Comment by domibron** [comment]
This issue is a result of level designers using the wrong prefab.
Path to correct prefab:
Assets/Prefabs/Elevator/Elevator (Working).prefab
