### ISSUE TITLE
[Frame-perfect jump on electrified water]

### ISSUE THREAD

**Issue by DonalDitas** [Smash-Keyboard-Studios/Meltdown#152]
If you time your second jump right, you can jump from electrified water surface without dying

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Level 6
2. Turn right from the elevator
3. get the jump timing right on the water surface

Upon colliding with electrified water, the player should die and send to the start of the level

Game Build 0.0.11

**Comment by Soph65536** [comment]
this will be an issue with the kill zones rather than the water itself
