### ISSUE TITLE
[BUG MAJOR] Office area has no collision

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#153]
**Describe the bug**
Many of the objects in the office area in level 3 do not have collision

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 3
2. Go to the office area
3. Walk through game objects

**Expected behavior**
These objects should have collision

**Game build num**
0.0.11

**Comment by Soph65536** [comment]
added colliders to the prefabs
