### ISSUE TITLE
[BUG] See void over lift

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#155]
**Describe the bug**
In level 3, if you look over the lift, the player can see the void.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 3
2. Get to the lift
3. Look above the lift
4. See void

**Expected behavior**
This should be blocked out to prevent the player from seeing it

**Screenshots**
![Level 3 See void](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/48ca7e5c-6073-470f-a7fb-8a1ff7b27a51)

**Game build num**
0.0.11

**Comment by MathewHakwkins** [comment]
Issue is still present in 0.0.12.

**Comment by MathewHakwkins** [comment]
Still present as of 0.0.14

**Comment by domibron** [comment]
also its not a elevator shaft

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.16
