### ISSUE TITLE
[BUG] See through lift

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#157]
**Describe the bug**
In level 4, when you reach the lift, you can see into it instead of a wall

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 4
2. Reach the lift
3. Go to the side of the lift
4. See into lift 

**Expected behavior**
There should be a wall or something that prevents the player from looking into the lift

**Screenshots**
![Level 4 See through lift](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/e7d4c8ce-9902-4609-a04d-4b318d9a1573)

**Game build num**
0.0.11

**Comment by BananaBros2** [comment]
Not actually an issue, was only placed here as a temporary solution to travel between levels. Will be only placed in walls
