### ISSUE TITLE
[BUG] Lift Has no collision

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#158]
**Describe the bug**
On level 5, the starting lift does not have Collision meaning the player can walk completely through it

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 5
2. Walk into lift walls
3. See error

**Expected behaviour**
The walls should have collision so the player cant just walk through it

**Screenshots**
![Level 5 Lift no collision](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/4a22108d-cbea-4d3a-8852-cca478e741c6)

**Game build num**
0.0.11

**Comment by Soph65536** [comment]
changed the prefab to contain mesh colliders. 
a different elevator prefab is being used for level 5 right now (elevatorstatic) so you may have to change it to the other elevator prefab (elevatorworking)since that is probably the one with functionality. :)
