### ISSUE TITLE
[ISSUE] No roof on level 6

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#160]
**Describe the bug**
On level 6, There is on roof

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 6
2. Look up
3. See there is no roof

**Expected behavior**
There should be a roof in the level

**Screenshots**
![Level 6 No roof](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/2b250629-e990-47e9-936a-0b50f438a147)

**Game build num**
0.0.11

**Comment by MathewHakwkins** [comment]
Issue is still present in 0.0.12.

**Comment by BananaBros2** [comment]
Level being remade, no longer an issue
