### ISSUE TITLE
Elevator does not close when player leaves [BUG]

### ISSUE THREAD

**Issue by domibron** [Smash-Keyboard-Studios/Meltdown#174]
**Describe the bug**
The elevator doors now need to close after the player has left the elevator.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go level 2 or higher (need to start in an elevator).
2. walk out while looking back to the elevator.

**Expected behavior**
Doors close

**Screenshots**

**Game build num**
0.0.12

**Comment by MathewHakwkins** [comment]
Issue is still present in 0.0.13
