### ISSUE TITLE
Clipping into the wall in lvl 2

### ISSUE THREAD

**Issue by DonalDitas** [Smash-Keyboard-Studios/Meltdown#176]
Player gets stuck in texture once he jumps to the designated area.

Steps to reproduce the behaviour:
1. Go to Level 2
2. Get to the second "parkour" room
3. Jump on one of the tiny ledges

In this particular area it is vital to make jumps for the player as smooth as possible, clipping into the walls will mess up the player and force them to drop to ground level and start again

Game Build 0.0.12

**Additional context**

**Comment by domibron** [comment]
Would love some screen shots.

**Comment by domibron** [comment]
Not a wall clip but the player jump check.
Working on a fix.
