### ISSUE TITLE
Lighting issues with furniture in level 1

### ISSUE THREAD

**Issue by DonalDitas** [Smash-Keyboard-Studios/Meltdown#177]
Once you get into the room with fallen ceiling, you will see that most of the furniture is pitch black while others has very bright colour

Steps to reproduce the behaviour:
1. Go to Level 1
2. Turn right inside the room

those models itself shouldn't be that unusually black or bright.

![IMG_0097](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834812/2b0f017c-6241-4424-b9de-90bdad660ab5)
![IMG_0098](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834812/d4faa31b-fbcd-4bd3-b2a7-1fb4ed825f7d)

Build 0.0.12

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.16
