### ISSUE TITLE
[BUG] Desk in wall

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#179]
**Describe the bug**
In level 1, a desk is stuck halfway through a wall

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 1
2. Go to the upper office room
3. Look at desk over the hole to go down

**Expected behavior**
This desk shouldn't be stuck in the wall

**Screenshots**
![Desk Clip](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/b93535a9-3de1-4186-92de-961e5c1b2e22)

**Game build num**
0.0.12

**Comment by MathewHakwkins** [comment]
After talking with Dion, this desk should be a filing cabinet.

**Comment by MathewHakwkins** [comment]
Still present as of 0.0.14

**Comment by domibron** [comment]
Prefab needs updating.

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.15
