### ISSUE TITLE
[BUG] Wall Prefabs Gone

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#194]
**Describe the bug**
Many of the prefabs for the walls and floors are gone. Levels affected: 1, 2, 4, 5, 6, 7 and 8

**To Reproduce**
1. Go into any level from list above
2. See Error

**Expected behavior**
There should be walls there they are missing

**Screenshots**
![Level 1 walls](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/1098a1ff-2c52-481f-aa21-7ee939ed21d9)

**Game build num**
0.0.13

**Comment by domibron** [comment]
This should be fixed

**Comment by domibron** [comment]
Fixed with 0.0.14
