### ISSUE TITLE
[BUG] Pause Menu Button is not working

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#195]
**Describe the bug**
When the player hits "Esc" nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level
2. Hit "Esc"
3. Nothing Happens

**Expected behavior**
When "Esc" is hit, the pause menu should show up

**Game build num**
0.0.13

**Comment by Soph65536** [comment]
it was braydens script !!!!
