### ISSUE TITLE
[BUG] Missing Object Collision

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#196]
**Describe the bug**
Many Objects are still missing collisions. These are in levels 3, 4, 5 and 9

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into Level 3, 4, 5
 or 9
2. Walk into current objects
3. See error

**Expected behavior**
There should be a collider box or something around the object

**Game build num**
0.0.17

**Additional context**
Please be very warry as to not create this issue in the future.

**Comment by MathewHakwkins** [comment]
Still Present In 0.0.14

**Comment by domibron** [comment]
how is this not fixed yet?
just add a mesh collider to the prefabs, and if they're not prefabs, them make them prefabs.

**Comment by MathewHakwkins** [comment]
Still present as of 0.0.17
