### ISSUE TITLE
[BUG] Fire Pedestal is missing

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#197]
**Describe the bug**
The fire pedestal is missing from levels.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into a level that has a fire pedestal
2. Go to where the pedestal is
3. See Error

**Expected behavior**
The fire Pedestal should be where it needs to be

**Screenshots**
![Fire pedistal Gone](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/09c50c38-65a4-4686-9dae-876face9a3a0)

**Game build num**
0.0.13

**Comment by domibron** [comment]
0.0.14
