### ISSUE TITLE
Elevator doors have been removed in Level 2

### ISSUE THREAD

**Issue by domibron** [Smash-Keyboard-Studios/Meltdown#210]
**Describe the bug**
Error in the console because elevator doors were removed due to a previous issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load level 2 (in editor).
2. Play the game.
3. Look at the console.

**Expected behaviour**
There should not be an error.

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/2402d1b3-8c6a-4c10-904f-9c30b2985967)

**Game build num**
0.0.13

**Additional context**
In editor.

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.16
