### ISSUE TITLE
Prefab in Level 2

### ISSUE THREAD

**Issue by domibron** [Smash-Keyboard-Studios/Meltdown#211]
**Describe the bug**
A random prefab in Level 2 prevents the player from leaving a room.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 2
2. Follow the 1st floor corridor.
3. The first open door on the left.
4. Attempt to enter.

**Expected behavior**
That should not be there.

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/d4f196dd-4523-4e2a-b77c-f2fc6e9b4fbd)
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/63b4d34d-001d-4b02-977e-49e2468c51e1)
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/9d22901b-4fbe-495e-bb86-1e4150e3d112)

**Game build num**
0.0.14

**Additional context**

**Comment by MathewHakwkins** [comment]
Button Has been moved to another room and doorframe is gone
