### ISSUE TITLE
collision issue on level 2, stairs.

### ISSUE THREAD

**Issue by domibron** [Smash-Keyboard-Studios/Meltdown#212]
**Describe the bug**
The player can get wedged between the stairs and railing causing a **soft lock**.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 2.
2. Jump onto the stairs.
3. Go to wards the slight opening between the railing and stairs.

**Expected behaviour**
The player does not get stuck.

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/1ae0de06-e2da-4e4c-ad13-dddc3f30fd78)

**Game build num**
0.0.14

**Additional context**

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.17
