### ISSUE TITLE
[BUG] Grab script bug

### ISSUE THREAD

**Issue by domibron** [Smash-Keyboard-Studios/Meltdown#221]
**Describe the bug**
The object's rotation is reset even though the cube is out of range and the grab key is pressed. (0-3m this seems to happen).
The object does not centre in the middle of the screen.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 12 (loadlevel 12)
2. Pick up the sclube.
3. See error.

**Expected behavior**
Cube will be in the middle of the screen.
Cube does not rotate if out of range.

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/f6b31c61-e161-4b25-8afc-ff08f8e1e624)
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/a380da65-5632-4591-bc9c-2a0f31578650)
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/98326467/22d236a8-a2c4-444a-87f2-332215f9baa2)

**Game build num**
0.014

**Additional context**

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.16
