### ISSUE TITLE
Level 2 Softlock

### ISSUE THREAD

**Issue by AshExistsSometimes** [Smash-Keyboard-Studios/Meltdown#223]
**Describe the bug**
There is a button pedestal blocking the doorway in the parkour section, which completely blocks you into the room

**Expected behavior**
There should not be a doorway blocking the door in the parkour section

**Screenshots**
![softlock](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156530724/2d8e1524-1e24-4e6b-b6ee-3ebf7e67ac7c)

**Game build num**
0.0.14

**Comment by domibron** [comment]
#211
