### ISSUE TITLE
Fire Tutorial Ice Walls Not Melting

### ISSUE THREAD

**Issue by AshExistsSometimes** [Smash-Keyboard-Studios/Meltdown#224]
**Describe the bug**
First 2 ice walls in fire tutorial level don't melt when hit with the fire ability, third one does

**To Reproduce**
Steps to reproduce the behaviour:
1. Loadlevel 4
2. Get Fire ability
3. Shoot ice wall

**Expected behavior**
Ice Walls should melt

**Game build num**
0.0.14

**Comment by domibron** [comment]
Can confirm these works form a programmer's standpoint.
this is a designer issue.

**Comment by MathewHakwkins** [comment]
Now Fixed in 0.0.15
