### ISSUE TITLE
[BUG] Note Issue

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#225]
**Describe the bug**
The name of the note in the UI is doesnt say note and when the note is active, the only way to turn it off is by hitting "ESC"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 1
2. Look at note (See first error)
3. Interact with note
4. press any key to close note
5. See error

**Expected behavior**
The UI should say it is a note and the note should close with the "E" Key

**Screenshots**
![Ineract Cube L1](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/23764c7f-a41c-46ff-80d5-89ff947afbad)

**Game build num**
0.0.14

**Comment by domibron** [comment]
Systems have been reworked and hopefully will be fixed after Wednesday

**Comment by MathewHakwkins** [comment]
Still present in 0.0.16 and now note does not work

**Comment by domibron** [comment]
Waiting for implementation

**Comment by RevisedDA** [comment]
Note asset still needs to be made by art team.
Please advise

**Comment by domibron** [comment]
ESC is the expected close method.
need to double-check some code.

**Comment by domibron** [comment]
Will add another close option
