### ISSUE TITLE
[BUG] Boiler Not heating fully

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#226]
**Describe the bug**
In level 3, when shooting the boiler, it will only heat up to the half way part then stop

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 3
2. Shoot fire projectile at boiler
3. shoot it more when it gets halfway

**Expected behavior**
The boiler should heat up fully

**Screenshots**
![Boiler not heating L3](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/f1938f44-ddbe-401a-acbf-3582d2c4229b)

**Game build num**
0.0.14

**Comment by Jakilutra** [comment]
It’s a new preset value for the testing scenario. It’s changing the scale from -90 to 90 because MinDegreesBelowStart is set to 90. So the fix should be to set it to 0 in the inspector. @domibron

**Comment by domibron** [comment]
Applied fix, waiting on result
