### ISSUE TITLE
[BUG] L5 No Roof

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#228]
**Describe the bug**
There is no roof on level 5

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 5
2. Look up
3. See error

**Expected behavior**
There needs to be a roof

**Screenshots**
![No Roof L5](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/97e5eb9e-3c3e-4c97-a349-3af3169cc027)

**Game build num**
0.0.14

**Comment by MathewHakwkins** [comment]
Still present as of 0.0.17

**Comment by RevisedDA** [comment]
Roofing will be resolved by Art team as it will be a modular asset.
