### ISSUE TITLE
[BUG] Door Missing

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#236]
**Describe the bug**
In level 4, a big door is missing leading to the void.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 4
2. Go to where the door is
3. See Error

**Expected behavior**
There needs to be a door there

**Screenshots**
![Z Fight And Door](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/61606378-8ed0-4d22-a332-39364bd1fccc)

**Game build num**
0.0.15

**Comment by MathewHakwkins** [comment]
Still present in 0.0.16

**Comment by domibron** [comment]
@Smash-Keyboard-Studios/designers

**Comment by MathewHakwkins** [comment]
Fixed as of 0.0.17
