### ISSUE TITLE
[BUG] Floating Water

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#237]
**Describe the bug**
In level 5, there is some floating water or something above the actual water

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 5
2. Freeze water and go onto it
3. Melt Ice Wall
4. See Error

**Expected behavior**
This does not need to be there

**Screenshots**
![Floating Water L5](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/ed67437d-3e9b-40ee-a108-08406c9bca20)

**Game build num**
0.0.15

**Comment by MathewHakwkins** [comment]
Still present in 0.0.16

**Comment by MathewHakwkins** [comment]
Upon further inspection, the floating water is caused by the melted ice wall

**Comment by domibron** [comment]
if thats the case then either programmers need to fix it or keep it as is.

**Comment by Soph65536** [comment]
made water puddles smaller

**Comment by MathewHakwkins** [comment]
Issue is not fixed as of 0.0.19
![L5 Ice Water](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/9e699ed3-c3d2-4530-9241-4b3ace156f2d)

**Comment by domibron** [comment]
will go over

**Comment by domibron** [comment]
no, i will not touch your scripts, they are safe... for now ; )

**Comment by domibron** [comment]
this needs to be a decal and not a png

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
