### ISSUE TITLE
[BUG] Box clip

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#245]
**Describe the bug**
In level 2, a box is clipping through the table it sits on.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 2
2. Get to the final area
3. Look at the side of the box
4. See Error

**Expected behavior**
The box should not be clipping through the table

**Screenshots**
![L2 Box Clip](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/3a1a5de4-ed12-4454-b67f-6c3d42136161)

**Game build num**
0.0.16

**Comment by RevisedDA** [comment]
Box Asset is okay
Table is not an artist made asset
