### ISSUE TITLE
[BUG] Fan Lights

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#247]
**Describe the bug**
In level 5, the fans have misplaced lights

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 5
2. Go to the fans
3. See Error

**Expected behavior**
Its unclear where the lights should be but definitely not in the air

**Screenshots**
![L5 Fan Lights](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/6ecb7d91-a120-4634-8dfc-5dc6d5ce9ead)

**Game build num**
0.0.16

**Comment by MathewHakwkins** [comment]
Still present as of 0.0.17

**Comment by RevisedDA** [comment]
The fan asset displayed here, has not been notified to the art team

There is an Fan that has been made by the art team, try to see if this can be used before resolve the lighting issue. if not. please notify me.
-Steve

**Comment by domibron** [comment]
This fan needs to be looked at and to be discussed mechanically.
@BananaBros2
