### ISSUE TITLE
[BUG] Moving platform not going high enough

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#248]
**Describe the bug**
In level 5, the moving platform to reach the elevator does not go high enough

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 5
2. Go to moving platform by the fans
3. See Error

**Expected behavior**
The platform need to go higher

**Screenshots**
![L5 Platform not rising high enough](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/7ad73621-9d66-45b5-b8c3-1f79ed351f0c)

**Game build num**
0.0.16

**Comment by BananaBros2** [comment]
Should be fixed in next build

**Comment by MathewHakwkins** [comment]
Platform is missing as of 0.0.17

**Comment by domibron** [comment]
> Should be fixed in next build

That failed hard
