### ISSUE TITLE
[BUG] Level 2 Box Soft Lock

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#262]
**Describe the bug**
In level 2, if the player grabs the cube and lets go of the cube when it's in the wall, the cube will fall out of the world and the player is stuck

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 2
2. Grab cube
3. Let go of cube when in wall
4. Be Stuck

**Expected behavior**
The cube should be able to respawn or the player can respawn it

**Screenshots**
![L2 Soft Lock](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/7701964f-f277-42eb-9dbb-ea479b3753cc)

**Game build num**
0.0.17

**Comment by domibron** [comment]
I did ask for this to be fixed, it seems like the work somehow got removed.
I'll forward it.

**Comment by domibron** [comment]
Making this into another issue

**Comment by domibron** [comment]
#308
