### ISSUE TITLE
[BUG] Level 6 Soft Lock

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#264]
**Describe the bug**
In level 6, if the player falls down onto the frozen water, the player will be soft locked

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 6
2. Freeze the water
3. Fall down
4. Be stuck

**Expected behavior**
There should be a way for the player to get out

**Screenshots**
![l6 Soft Lock](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/99f1887e-84ce-4a26-8fdd-a2190336c85b)

**Game build num**
0.0.17

**Comment by domibron** [comment]
@BananaBros2 
What is the expected result?
