### ISSUE TITLE
[BUG] Floating Balls

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#266]
**Describe the bug**
In level 9, in each room are two floating balls

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 9
2. Enter any room
3. See Balls

**Expected behavior**
There shouldn't be any balls

**Screenshots**
![L9 Floating Balls](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/58b40839-2d4e-456d-8e1f-480cbd7425d9)

**Game build num**
0.0.17

**Comment by domibron** [comment]
Floating balls.
ah yes.
