### ISSUE TITLE
[BUG] Box can be phased through walls 

### ISSUE THREAD

**Issue by domibron** [Smash-Keyboard-Studios/Meltdown#308]
**Describe the bug**
pickup objects can be placed through the wall.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any level with a pickup object.
2. pick it up.
3. walk to a wall.
4. press e.
5. Look.

**Expected behaviour**
The cube should have a collision with the wall.

**Screenshots**

**Game build num**
0.0.18

**Additional context**

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
