### ISSUE TITLE
[BUG] Player can get stuck in sliding doors

### ISSUE THREAD

**Issue by Soph65536** [Smash-Keyboard-Studios/Meltdown#313]
**Describe the bug**
if the player walks into the doorway and it closes on them then they get stuck in it and cannot move

**To Reproduce**
Steps to reproduce the behaviour:
1. open a sliding door
2. walk into the doorway
3. wait for it to close on you
4. player cannot move!

**Expected behavior**
player can walk out of the doorway once it is shutting

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156205204/5e6a9b45-54cb-4f6b-b76e-c6c606a32f02)

**Game build num**
Look for the game build number.

**Additional context**

**Comment by domibron** [comment]
will get someone on this
