### ISSUE TITLE
[BUG] Player gets stuck on platforming

### ISSUE THREAD

**Issue by JunoGrice20** [Smash-Keyboard-Studios/Meltdown#314]
**Describe the bug**
On the 2nd platforming section of the office level, the player is able to get stuck in certain sections of the environment when jumping. such as: If the player jumps at the side of the stairs, the player will get stuck and not be able to move at all unless they crouch to get out, this same thing happens if you try jumping to the top left corner of the platform after the stairs that you need to jump to.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the 2nd platforming section of the office level
2. head to the gap where you can touch the side of the stairs
3. Jump and move forwards and you should be stuck, press c to unstick yourself
4. I have been unable to reproduce the other bug but you need to try and jump to the top left corner of the platform from the stairs and you should get stuck, again crouch to free yourself.

**Expected behavior**
The player will get stuck and be unable to move unless crouching.

**Screenshots**
![stairs](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158371043/9e946366-19c2-4c0c-9cc1-af39c43015ba)
![2nd platform](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158371043/55b4cbfd-564f-4011-ab78-33730a8e1c45)

**Game build num**
0.0.19

**Additional context**

**Comment by domibron** [comment]
will get someone on this
