### ISSUE TITLE
Level 1 walls [BUG]

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#316]
Level 1 office walls, incorrect light maps on the office walls. 

![Light map office walls](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/c130c798-800f-48eb-bf52-95389ac7ee39)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Game build num**
Look for the game build number.

**Additional context**

**Comment by domibron** [comment]
will get someone on this

**Comment by MathewHakwkins** [comment]
Closed for organisation
