### ISSUE TITLE
General lighting LVL1[BUG]

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#317]
General lighting within LVL 1 office section needs to be improved or increase the amount, it is just too dark 

![Office lighting ](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/fc9187d4-942b-4210-bd22-012f98d29c75)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Game build num**
Look for the game build number.

**Additional context**

**Comment by MathewHakwkins** [comment]
Closed for Organisation
