### ISSUE TITLE
[BUG] Wire in level 2 

### ISSUE THREAD

**Issue by UsernamesAreTooHard** [Smash-Keyboard-Studios/Meltdown#319]
Basically if you press the button multiple times in level 2, the wire leading from the button to the elevator can get desynced with the door.

Steps to reproduce the behaviour:
1. Go to the only button in level 2
2. Click on the button twice quickly
3. See error where the light of the wire goes off but the door stays open
4. now the wire is desynced 

I expect pressing the button multiple times to not turn the wire off, or if it does turn the wire off than to turn the door off along with it. 

![Screenshot 2024-04-19 125714](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156562533/62c4f3a8-a1ad-41f1-8de4-a064f9d8d6b7)

build number 0.0.19

bugs not game breaking so not high priority

**Comment by domibron** [comment]
will have someone look into this
