### ISSUE TITLE
[EMPROVEMENT] Debris and Rock props

### ISSUE THREAD

**Issue by louisetia** [Smash-Keyboard-Studios/Meltdown#321]
**Describe the bug**
The debris props - 4 different rock types and 2 collapsed wall types - need to be added to the game where deemed necessary

![debris](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157993835/8b20d0e6-f637-45c3-80c4-73a52b3fe88d)

**Comment by domibron** [comment]
LOD of these also need to be created. (ME)
Will let design know

**Comment by MathewHakwkins** [comment]
Level 4 is in need of more rocks
