### ISSUE TITLE
Lvl 2 Wooden wall poking through the elevator at the start of lvl 2[BUG]

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#325]
Wooden wall poking through the wall of the elevator at the start of lvl 2

![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/6d45b568-3be8-48d6-b033-612058b963c6)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Game build num**
Look for the game build number.

**Additional context**

**Comment by domibron** [comment]
will have someone look into this

**Comment by MathewHakwkins** [comment]
Closed for Organisation
