### ISSUE TITLE
Level 2 Lightmaps on all walls need fixing [BUG]

### ISSUE THREAD

**Issue by louisetia** [Smash-Keyboard-Studios/Meltdown#326]
Level 2 Lightmaps on all walls need fixing 
![lightmaps](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157993835/7716ce18-02c6-4cae-8e69-dc97f8c2d329)

**Comment by domibron** [comment]
This is being looked in, it seems to be with the model.

**Comment by MathewHakwkins** [comment]
Closed for Organisation
