### ISSUE TITLE
[BUG] Backflips on high sensitivity 

### ISSUE THREAD

**Issue by DonalDitas** [Smash-Keyboard-Studios/Meltdown#327]
While playing the game on high sensitivity, player doesn't have any restrictions on a camera, so he can move the camera in the angles he wasn't meant to rotate.

Steps to reproduce the behaviour:
1. Start the new game
2. go to options section in menu
3. set your sensitivity on 5+
4. Press "Quit Game" in menu
5. Press "New Game"
6. See the issue

Player should have restriction on y and x axis to prevent "backflips" from happening.

![Untitled](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834812/0c0c0714-5eae-47df-9f52-5f09f6ca1e01)

Build 0.0.19

**Comment by domibron** [comment]
this will be fixed monday

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
