### ISSUE TITLE
[BUG] Lvl 2 Player Soft lock

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#328]
Get stuck under the stairs and cant crouch out of the lock lvl 2 staircase 

![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/626c65b9-055a-4d67-b5c7-7e23bb0b20df)

**Game build num**
0.0.19

**Comment by domibron** [comment]
Will get someone to look into this
