### ISSUE TITLE
[BUG] Level 3 Player can get stuck

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#330]
**Describe the bug**
In level 3 you can get stuck by trying to climb onto a pipe and crouching

**To Reproduce**
Steps to reproduce the behaviour:
go into level 3
try to climb pipe and crouch
get stuck

**Expected behavior**
dont get stuck

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/769f7f6b-cb12-47ad-8c3c-7cf6b52aa821)

**Game build num**
0.0.19

**Additional context**

**Comment by domibron** [comment]
will have someone on this

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
