### ISSUE TITLE
[EMPROVEMENT] Signpost on the staircase

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#331]
We need an indicator to guide the player through the doorway, and also some rubble to block off the staircase to stop players wasting time going all the way up the stairs. 

![Adding rubb](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/27184e2c-bb0e-4366-abff-bbb5623aeafb)

**Game build num**
0.0.19

**Comment by domibron** [comment]
thinking of signs, will get someone on this
