### ISSUE TITLE
Level 4 Can walk through the elevator door [BUG]

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#332]
**Describe the bug**
You can walk through the elevator door and fall out of the world

**To Reproduce**
Steps to reproduce the behaviour:
Open level 4 
walk into the highlighted area
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/3949686c-31c5-4bac-902b-d2258618d6f0)

**Expected behavior**
not be able to walk through the wall

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/64f237cc-44f0-44e4-9dec-ce548fe1b6cb)

**Game build num**
0.0.19

**Additional context**
the same elevator is used on other scenes and twice in this scene, you can walk through it on both ends, start and finish

**Comment by domibron** [comment]
will have someone look into this

**Comment by MathewHakwkins** [comment]
Closed for Organization
