### ISSUE TITLE
[BUG] Floating door 

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#334]
**Describe the bug**
There is a floating door and it is not burnable even though it is a wooden door

**To Reproduce**
Steps to reproduce the behaviour:
Open level 4,
walk forward
See Error

**Expected behavior**
door to be on the ground

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/d5ed3f30-1469-432d-ae71-801cfd3510ef)

**Game build num**
0.0.19

**Additional context**
there is a fire pedestal right next to it and it cant burn from it.

**Comment by domibron** [comment]
the door model is slightly smaller than the frame

**Comment by MathewHakwkins** [comment]
As of 0.1.21, the door is missing

**Comment by MathewHakwkins** [comment]
New Door is Present
