### ISSUE TITLE
Clipping on the wall in level 2[BUG]

### ISSUE THREAD

**Issue by UsernamesAreTooHard** [Smash-Keyboard-Studios/Meltdown#335]
the bug is that a wall near the end of the level clips through a wall panel 

Steps to reproduce the behaviour:
1. Go to the end of level 2 
2. look between the box where you get the gun and the warning door
3. watch the wall flicker 

I expect the wall to not flicker and flash

![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156562533/a87aee19-c9c6-4196-8eea-42c96183cad0)

game build number 0.0.19

**Comment by domibron** [comment]
models have been made
