### ISSUE TITLE
Level 4 Generator no collision[BUG]

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#336]
**Describe the bug**
There is no collision for all generators spread across the map

**To Reproduce**
Steps to reproduce the behaviour:
Go to level 4
find any generator
walk into generator
walk through generator

**Expected behavior**
generator to have collision

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/f9bbad5a-1d80-4ca0-832d-eecd56faae09)

**Game build num**
0.0.19

**Additional context**

**Comment by domibron** [comment]
will get someone to look into this

**Comment by MathewHakwkins** [comment]
Closed for Organisation
