### ISSUE TITLE
[EMPROVEMENT] Lab cabinets sizes

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#337]
The blue cabinets in lvl 2 labs are a different size they should be the same size. 

![Blue cabinates](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/361cfeb5-53f3-432c-b6de-5acbc5bb8ac7)

**Game build num**
0.0.19

**Comment by domibron** [comment]
will have someone looking into this
