### ISSUE TITLE
[BUG] Level 3 softlock

### ISSUE THREAD

**Issue by X-Callum-X** [Smash-Keyboard-Studios/Meltdown#338]
**Describe the bug**
Soft lock on level 3

**To Reproduce**
Steps to reproduce the behaviour:
1. Place both crates on both buttons to open the designated door
2. Begin to push one of the buttons off of its respective button
3. Immediately run towards the door and enter the room
4. The door will shut behind you and you will be stuck in the room

**Expected behavior**
It should not be possible to reach this room before the door shuts

**Game build num**
0.0.19

**Comment by domibron** [comment]
interesting, will get someone to look into this

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
