### ISSUE TITLE
Level 4 Railing collision issue[BUG]

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#339]
**Describe the bug**
Some railings on level 4 have no collision

**To Reproduce**
Steps to reproduce the behaviour:
go to level 4
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/299f0a7f-cd19-42b1-ae8a-9ab0a97582ca)
walk into railing
walk through railing

**Expected behavior**
railing should have collision

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/455f0fde-5a9f-4028-928a-7c43114dd394)

**Game build num**
0.0.19

**Additional context**
this is used around the map and has no collision

**Comment by domibron** [comment]
will get someone on that

**Comment by MathewHakwkins** [comment]
Closed for Organisation
