### ISSUE TITLE
[BUG] Windows see through world

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#343]
**Describe the bug**
You can jump at where there should be windows / curtains and fall into the void

**To Reproduce**
Steps to reproduce the behaviour:
Go to level 4 
go near the end
find these
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/8316cf79-bba4-4fcd-920e-7322a04f1e75)
crouch jump into spot
walk out and fall into void

**Expected behavior**
should not be able to jump through / see through these

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/600c4bb1-67ac-4955-b918-fd17bbadb25c)

**Game build num**
0.0.19

**Additional context**

**Comment by domibron** [comment]
will push to desgin

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
