### ISSUE TITLE
[EMPROVEMENT] Level 3 labs dressing

### ISSUE THREAD

**Issue by louisetia** [Smash-Keyboard-Studios/Meltdown#345]
the lab needs much more of the microscopes, Bunsen burner props added, 1 or 2 per desk section/station
there are also 2 variations of the microscopes so these should be added

![cabinetprops](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157993835/9c852774-e0c3-4249-b592-a578327df92b)

**Comment by domibron** [comment]
will push to design
