### ISSUE TITLE
[BUG] Gun cases

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#346]
**Describe the bug**
You can press e on the gun cases and "pickup gun"

**To Reproduce**
Steps to reproduce the behaviour:
Go to level 4
find gun cases near the end
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/76529e65-a97c-4b61-9f29-502740c1b537)
press e on gun cases and find that they open with the prompt "pickup gun"

**Expected behavior**
should not be showing anything to pickup gun or open cases

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/f2a40216-9145-4f98-98c9-aaea7e9d2e32)
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/2a4d61f8-ccbe-4d26-9279-ba9a81de7fc7)
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/433b89e4-4011-4f0b-a6db-0c5825dac1df)

**Game build num**
0.0.19

**Additional context**
they can be opened but do nothing

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
