### ISSUE TITLE
[BUG] Missing ammo capsules on gun 

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#347]
Ammo capsules only have one texture on them there are plenty more in the game files. 

![Missing ammo capsuals textures](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/08ceb78f-2c7f-4848-9cb5-f85e7a06918f)

**Game build num**
0.0.19

**Comment by domibron** [comment]
Will look into this as I personally used the textures, I may have forgotten to override the prefab.
