### ISSUE TITLE
[BUG] Computer and Button are not on the ground

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#349]
**Describe the bug**
Computer and button are not on the ground

**To Reproduce**
Steps to reproduce the behaviour:
Go to level 4, near the end and find button and computer 
they are not on the floor
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/dcf06c75-a607-4585-a91c-20e9fd644c73)

**Expected behavior**
they should be on the floor

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/37e6311f-a000-4651-aed7-137057b08ae6)

**Game build num**
0.0.19

**Additional context**
this happens in other levels too or maybe more times in this level ( should check all levels for this)

**Comment by domibron** [comment]
will forward

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
