### ISSUE TITLE
[BUG] Level 4 - Crystals not staying in the crate on moving platform

### ISSUE THREAD

**Issue by X-Callum-X** [Smash-Keyboard-Studios/Meltdown#350]
**Describe the bug**
All but one of the crystals in the crate on the first moving platform on level 4 don't stay in the crate as they should

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Level 4
2. Enter the cave area
3. Look at the first moving platform in this area
4. See this issue

**Expected behavior**
The crystals should stay in the crate and move up and down with the moving platform

**Screenshots**
![Crystals](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156833966/bfb82c3e-7390-41b8-9605-cbe5ab414ea2)

**Game build num**
0.0.19

**Comment by domibron** [comment]
needs childing

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
