### ISSUE TITLE
[BUG] Level 4 sliding door 

### ISSUE THREAD

**Issue by odinx311** [Smash-Keyboard-Studios/Meltdown#358]
**Describe the bug**
this door can be opened by pressing e on it.
it can also be opened by pressing the button

**To Reproduce**
Steps to reproduce the behaviour:
go to level 4
go to this door
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/eda25243-ad8e-4539-b5fe-20ef4c8c22fc)
press e on door

**Expected behavior**
only the buttons should be able to open the door

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157402743/fb65e676-0c56-4395-abe1-9a03c916e429)

**Game build num**
0.0.19

**Additional context**
some other doors do/did this too

**Comment by domibron** [comment]
On the door hinge (child) there is a bool that says is player interactable. Just set that to off.
