### ISSUE TITLE
[BUG] Brick work in geometry 

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#359]
This brickwork is geometry, needs to be changed to height map and a texture

![Brick walls](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/6cc2aebb-5f36-445d-ae32-e142aee11ef3)

**Game build num**
0.0.19

**Comment by domibron** [comment]
It's lagging the game a little too.
