### ISSUE TITLE
[EMPROVEMENT] Crates need to have things in them

### ISSUE THREAD

**Issue by louisetia** [Smash-Keyboard-Studios/Meltdown#360]
All the crates on level 4 are empty, crystals or any prop should be filling some/all of these so they have a use 

They also could be scaled down slightly 

![crate](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157993835/b0caa7fd-a842-45a5-8996-8e4a29ce6265)

**Comment by domibron** [comment]
Also, the texture needs to be replaced.

**Comment by domibron** [comment]
Will point out a p3/p2 issue is that players cannot simply jump out without a crouch jump.
