### ISSUE TITLE
[BUG] Collider preventing progress in Level 5

### ISSUE THREAD

**Issue by X-Callum-X** [Smash-Keyboard-Studios/Meltdown#361]
**Describe the bug**
The player can't leave the lift in level 5 and play the level due to a collider being in the way of the lift exit

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Level 5
2. Try to leave the lift
3. See that you can't

**Expected behavior**
The player should be able to leave the lift and play the level

**Game build num**
0.0.19

**Comment by domibron** [comment]
This will need to be fixed after Adam's audio pass.

**Comment by domibron** [comment]
I managed to locate the issue.
The airlock doors had their mesh renderers turned off but not the whole object.
simply turn off the collider or game object (the door)

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
