### ISSUE TITLE
[BUG] Floating Laiths

### ISSUE THREAD

**Issue by louisetia** [Smash-Keyboard-Studios/Meltdown#362]
level 5 Laiths are floating above the ground and scaled slightly too big 
![laith](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157993835/ec273647-fc1e-4574-9a7a-5c70cc51d369)

**Comment by domibron** [comment]
--

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
