### ISSUE TITLE
[BUG] Hydraulic press floating 

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#363]
Hydraulic press floating and has been stretched scale wise its too high 

![Hydraulic press stretched](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/ca1a86ae-dfb5-471d-9adc-f141d6926734)

**Game build num**
0.0.19

**Comment by domibron** [comment]
Noted.

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
