### ISSUE TITLE
[BUG] Fume hood tubes

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#365]
Fume hood has floating tubes the additions have been added to the game they just need to be implimented [BUG]

![Floting fume hood tubes](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/f8129145-cfe5-4a57-b40e-39aca41020ad)

**Game build num**
0.0.19

**Comment by domibron** [comment]
Amazing.
@BananaBros2 
Forward to design team.

**Comment by domibron** [comment]
Level 4 both lab areas
