### ISSUE TITLE
[EMPROVEMENT] most light sources need a lightbulb/shade model

### ISSUE THREAD

**Issue by louisetia** [Smash-Keyboard-Studios/Meltdown#366]
lampshades/hanging bulbs need to be added to the game 
![lights](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/157993835/f8cba1a8-3c1f-40cf-8fc9-c4496584c99d)

**Comment by domibron** [comment]
@ilovefortnite72 
You get to have more fun with lights.
Most levels are missing light models.
I added light probes but you may need to adjust them. [Vid](https://youtu.be/3J9FpXqRoos?si=zi-NY4cNrALd6LQL). They are very badly placed and not being used properly too so If you can adjust the light probes.
+ Making anything that is decor static would be nice.
Also light maps seem to not be good at 40 res, try a 100 res or higher (based on level 2).
