### ISSUE TITLE
[ISSUE] Level 5 - First puzzle can be skipped

### ISSUE THREAD

**Issue by X-Callum-X** [Smash-Keyboard-Studios/Meltdown#367]
**Describe the bug**
The first puzzle with the elemental core and the moving platforms can be skipped by platforming on the crates on the right side of the room

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Level 5
2. Press the button which takes you down to the first puzzle
3. See the boxes on the right side of the room entrance
4. Parkour on these boxes and crouch-jump onto the wall
5. You have skipped the first puzzle

**Expected behavior**
These crates should be moved so that you can't skip this puzzle

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156833966/66241906-95d7-4f1b-ae5a-9d7a91c3baaa)

**Game build num**
0.0.19

**Comment by domibron** [comment]
--

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
