### ISSUE TITLE
[BUG] Player can clip through moving platform

### ISSUE THREAD

**Issue by X-Callum-X** [Smash-Keyboard-Studios/Meltdown#368]
**Describe the bug**
If the quick moving platform in level 5 is stood on before being frozen, the player will sometimes clip through the bottom of the platform as it rises

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Level 5
2. Go down the tunnel to the underground area
3. Locate the quick moving platform in this area
4. Stand on the moving platform without freezing it
5. See the issue

**Expected behavior**
The player probably shouldn't be able to stand on top of the platform while it's moving at this speed. Either that, or rework it

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156833966/98ff1ba4-b8aa-4735-b957-ccf0f05ee380)

**Game build num**
0.0.19

**Comment by domibron** [comment]
Kill zones do not work

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
