### ISSUE TITLE
[BUG] Stone wall textures 

### ISSUE THREAD

**Issue by UsernamesAreTooHard** [Smash-Keyboard-Studios/Meltdown#369]
the wall textures in the cave very clearly have adobe watermarks  

Steps to reproduce the behaviour:
1. Go to level 4
2. look at the walls 

i expect the walls to use the lovely textures Juno made 

![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156562533/5792067a-4153-433b-9a01-1422b4b7d1ff)
is this a joke? ^

game build 0.0.19

**Comment by domibron** [comment]
Rock texture needs an actual texture map and to be world space and tileable.

**Comment by domibron** [comment]
I believe that there is a material made

**Comment by RevisedDA** [comment]
I do not think that is the material that has been made for our rock textures. 

There is also currently no rock models that I am aware of
