### ISSUE TITLE
[BUG] Gun Firing 

### ISSUE THREAD

**Issue by CH3W13** [Smash-Keyboard-Studios/Meltdown#371]
![Gun infinate amm but cant fire](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/158067054/c070fbec-d68e-4807-bc04-fe04a59483aa)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**Game build num**
Look for the game build number.

**Additional context**

**Comment by MathewHakwkins** [comment]
Closed for Organisation
