### ISSUE TITLE
[BUG] Ice wall doesn't shrink

### ISSUE THREAD

**Issue by X-Callum-X** [Smash-Keyboard-Studios/Meltdown#372]
**Describe the bug**
The model for the ice wall in level 7 doesn't shrink when melted, but the hitbox does

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Level 7
2. Locate the ice wall
3. Shoot fire at it
4. See the issue

**Expected behavior**
The ice wall model should scale as intended

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156833966/dff6e7bd-1a18-4cca-93aa-662caa7d0f83)

**Game build num**
0.0.19

**Comment by domibron** [comment]
@AshExistsSometimes 
I may accidentally made this static when I was doing the quick light pass.

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.21
