### ISSUE TITLE
[BUG] Lightmaps

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#386]
**Describe the bug**
Lightmaps on Levels 1, 2 and 3 need to be reworked as textures are messed up

**Expected behavior**
Textures should work properly with lighting

**Screenshots**
![L1 Wall textures](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/7d6adff9-fa93-467f-8490-b3ddbc5c0116)
![L2 Wall + Floor Textures](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/06eee60b-738d-4714-b6ec-a1fafaddb882)

**Game build num**
0.0.19.

**Comment by RevisedDA** [comment]
Where i first thought this was an issue on my end, I was informed that my models and textures dont have this issue recurring in later levels.

This must be a lighting issue with the lighting build itself and not the models. the floors would not of been affected this way if it was my models as well as they are simple flat planes.

**Comment by MathewHakwkins** [comment]
Fixed as of 0.1.23
