### ISSUE TITLE
[Design Issue] Door in level 4

### ISSUE THREAD

**Issue by X-Callum-X** [Smash-Keyboard-Studios/Meltdown#396]
**Describe the bug**
Upon exiting the lift in level 4, you can see that there's a missing door in the room you enter, allowing you to go straight to the end of the level.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to level 4
2. Exit the lift
3. See the issue

**Expected behavior**
This door should be here to prevent the player from effectively skipping the level.

**Screenshots**
![image](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156833966/2db41a48-f91b-4032-9a46-90223763c3ac)

**Game build num**
0.1.21

**Comment by MathewHakwkins** [comment]
[Linked to Floating Door Issue](https://github.com/Smash-Keyboard-Studios/Meltdown/issues/334)

**Comment by MathewHakwkins** [comment]
Door is Fixed but Door frame has no collision so player can still go through
