### ISSUE TITLE
[BUG] Level 8 Doors

### ISSUE THREAD

**Issue by MathewHakwkins** [Smash-Keyboard-Studios/Meltdown#438]
**Describe the bug**
The doors in level 8 does not open when the button is pressed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into level 8
2. Go to Door
3. Press interact on button
4. See Error

**Expected behavior**
The door should open when the button is pressed

**Screenshots**
![Level 8 Door](https://github.com/Smash-Keyboard-Studios/Meltdown/assets/156834847/116acd71-1459-4e15-9c2f-8aeba14d7ccc)

**Game build num**
0.1.23

**Additional context**
Please Fix ASAP

**Comment by lordodin92** [comment]
fixed issue door was set to static
